---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
```

```{r}
data("instacart")
set.seed(66)
order=unique(instacart|>pull(order_id))
data_sample=instacart|>
  filter(order_id %in% sample(order,1000))
```

Column {data-width=650}
-----------------------------------------------------------------------

### The most popular aisles

```{r}
data_sample |> 
  count(aisle,name="n_items")|>
  arrange(desc(n_items))|>
  filter(n_items>100)|>
  mutate(aisle = forcats::fct_reorder(aisle, desc(n_items)))|>
  plot_ly(y=~n_items,x=~aisle,color = ~aisle,type = "bar",colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### The order hour of the day among popular aisles

```{r}
top_aisle=data_sample |> 
  count(aisle,name="n_items")|>
  arrange(desc(n_items))|>
  filter(n_items>200)|>
  pull(aisle)
data_sample|>
  filter(aisle %in% top_aisle)|>
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box", colors = "viridis")
```

### The number of orders in each weekday

```{r}
data_sample|>
  mutate(order_dow=recode(order_dow,
                          "0"="Sunday","1"="Monday","2"="Tuesday","3"="Wednesday","4"="Thursday","5"="Friday","6"="Saturdy"))|>
  mutate(order_dow=forcats::fct_relevel(order_dow,c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturdy")))|>
  count(order_dow,name="n_items")|>
  plot_ly(y=~n_items,x=~order_dow,color = ~order_dow, type = "scatter",colors = "viridis",mode="markers")
```

